FROM alpine:3.12 

ARG GITHUB_TOKEN=""

RUN apk add bash python3 git expect py3-pip g++ libc-dev python3-dev linux-headers
RUN pip3 install html5lib
RUN pip3 install Brotli
RUN pip3 install psutil
RUN pip3 install dataclasses-json

WORKDIR /

COPY build_cats.py /
COPY dcachebase.py /
COPY dcache.py /
ADD  scrapscrap /
COPY scrapscrap /scrapscrap

COPY build/build-html-in-docker.sh /
COPY build/ex /

COPY description_cache.json / 

RUN GITHUB_TOKEN=${GITHUB_TOKEN} ./build-html-in-docker.sh





