FROM alpine:3.12 

ARG GITHUB_TOKEN=""

RUN apk add bash python3 git expect py3-pip
RUN pip3 install python-geoip
RUN pip3 install python-geoip-geolite2
RUN pip3 install maxminddb 
RUN pip3 install maxminddb-geolite2
RUN pip3 install dataclasses-json





